config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
      resources :posts, except: [:edit, :update, :destroy] do
        resources :comments, only: :create
    end

      get '/login' => 'sessions#new'
      post '/login' => 'sessions#create'
      get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'


end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post

    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments

    def date_published
        created_at.localtime.strftime("%A, %B %-d, %Y at %l : %M %p")
    end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

      def authorize
        redirect_to '/login' unless current_user
      end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(comment_params)
        @comment.user = current_user
        @comment.save
        redirect_to @post
    end

    private

    def comment_params
        params.require(:comment).permit(:body)
    end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path
        else
            render "new"
        end
    end

    def show
        @post = Post.find(params[:id])
        @comment = @post.comments.new


    end

    private
        def post_params
            params.require(:post).permit(:title, :body)

        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
# added these lines.
<% if current_user %>
  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>

<%= yield %>
<%= params %>
</body>
</html>

app/views/posts/index.html.erb
<h1>Claude's Blog</h1>
<div class="container">
<ul class="list-unstyled">
    <% @posts.each do |p| %>
    <li><h2><%= p.title %></h2></li>
    <li><%= p.body %></li>
    <li><%= link_to "Post URL", post_path(p), class: "btn btn-primary btn-xs" %></li>
    <% end %>
</ul>
</div>
<div class="container">
    <%= link_to "Create Post", new_post_path, class: "btn btn-success btn-lg" %>
</div>

app/views/posts/new.html.erb
<h1>New blog post</h1>

<%= form_for @post do |f| %>
    <ul class="list-unstyled">
        <div class="form-group">
        <li><h2><%= f.label :title %></h2></li>
        <li><%= f.text_field :title, class: "form-control" %></li>
        </div>
        <div class="form-group">
        <li><%= f.label :body %></li>
        <li><%= f.text_area :body, class: "form-control" %></li>
        </div>
<%= f.submit "Post", class: "btn btn-default" %>
    <ul>
<% end %>

app/views/posts/show.html.erb
<div class="cols"
<h1 class="bg-success"><%= @post.title %></h1>
<p class="bg-info"><%= @post.body %></p>
<p class="bg-info"><%= @post.date_published %></p>
<% @post.comments.each do |comment| %>
<%= comment.body %>
<% end %>
<div class="container">
<%= link_to "All posts", posts_path, class: "btn btn-warning btn-sm" %>
</div>



<%= form_for ([@post, @comment]) do |f| %>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <br>
    <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>